import os
import unittest
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch
from uuid import uuid4

from sqlalchemy.pool import NullPool
from sqlmodel import Session, SQLModel, create_engine, select

from app import database
from app.config import settings
from app.models import PackCreditAccount, PackCreditLedger, Purchase, StripeEvent
from app.pack_credits import _event_fingerprint, process_stripe_purchase_event


MIGRATIONS = (
    "20260807_commercial_foundation.sql", "20261002_pack_credit_ledger.sql",
    "20261003080058_pack_credit_engine.sql", "20261003085650_pack_credit_column_defaults.sql",
    "20261003093309_custom_manual_pack_topup.sql", "2026100901_payment_orders_events.sql",
    "2026100902_credit_lots_refunds.sql", "2026100903_stripe_checkout_webhook.sql",
)


def _reset_postgres(url, migrations=MIGRATIONS):
    import psycopg

    with psycopg.connect(url) as connection:
        if "test" not in connection.info.dbname.lower():
            raise RuntimeError("PACK_CREDIT_TEST_DATABASE_URL must identify a test database")
        connection.execute("drop schema if exists public cascade")
        connection.execute("drop schema if exists auth cascade")
        connection.execute("create schema public")
        connection.execute("create schema auth")
        connection.execute("create table auth.users (id uuid primary key)")
        connection.execute("create function auth.uid() returns uuid language sql stable as 'select null::uuid'")
        connection.execute("""
            create table public.generationusage (
                id bigint generated by default as identity primary key,
                user_id uuid not null, application_id integer, pack_id uuid not null,
                generated_at timestamptz not null, completed_at timestamptz
            )
        """)
        root = Path(__file__).resolve().parents[2] / "supabase" / "migrations"
        for name in migrations:
            connection.execute((root / name).read_text(encoding="utf-8"))


class PaymentEventTransactionTests(unittest.TestCase):
    def setUp(self):
        self.temp = TemporaryDirectory(dir=Path(__file__).parent)
        self.engine = create_engine(
            f"sqlite:///{Path(self.temp.name) / 'payments.db'}",
            connect_args={"check_same_thread": False},
            poolclass=NullPool,
        )
        SQLModel.metadata.create_all(self.engine)

    def tearDown(self):
        self.engine.dispose()
        self.temp.cleanup()

    def test_online_create_all_excludes_migration_only_payment_tables(self):
        with patch.object(settings, "deployment_mode", "online"):
            names = {table.name for table in database._create_all_tables()}
        self.assertTrue(database.MIGRATION_ONLY_TABLES.isdisjoint(names))

    def test_checkout_operational_schema_is_declared_but_never_created_at_startup(self):
        purchase_columns = set(Purchase.__table__.columns.keys())
        event_columns = set(StripeEvent.__table__.columns.keys())
        self.assertTrue({
            "livemode", "expires_at", "refund_detected_at",
            "checkout_idempotency_key_hash", "gst_enabled",
        }.issubset(purchase_columns))
        self.assertTrue({
            "livemode", "failure_reason_code", "stripe_object_id",
        }.issubset(event_columns))
        self.assertTrue({
            "paymentcheckoutrate", "paymentoperationaudit",
        }.issubset(database.MIGRATION_ONLY_TABLES))

    def test_failed_processing_rolls_back_records_failure_and_reraises_then_retries_once(self):
        user_id = uuid4()
        facts = dict(
            stripe_event_id="evt_retry_once",
            stripe_checkout_session_id="cs_retry_once",
            stripe_payment_intent_id="pi_retry_once",
            user_id=user_id,
            package_code="single",
            credits=1,
            subtotal_cents=1695,
            gst_cents=0,
            total_paid_cents=1695,
            single_pack_price_cents=1695,
            currency="AUD",
        )

        with Session(self.engine) as session, patch(
            "app.pack_credits._grant_pack_credits", side_effect=RuntimeError("transient database failure")
        ):
            with self.assertRaisesRegex(RuntimeError, "transient database failure"):
                process_stripe_purchase_event(session, **facts)

        with Session(self.engine) as session:
            event = session.get(StripeEvent, "evt_retry_once")
            self.assertEqual((event.status, event.attempt_count), ("failed", 1))
            self.assertIsNone(session.exec(select(Purchase)).first())
            self.assertIsNone(session.get(PackCreditAccount, user_id))

        with Session(self.engine) as session:
            first = process_stripe_purchase_event(session, **facts)
            repeated = process_stripe_purchase_event(session, **facts)

        with Session(self.engine) as session:
            event = session.get(StripeEvent, "evt_retry_once")
            grants = session.exec(select(PackCreditLedger).where(
                PackCreditLedger.entry_type == "grant_stripe_purchase"
            )).all()
            self.assertEqual((first, repeated), (3, 3))
            self.assertEqual((event.status, event.attempt_count), ("processed", 2))
            self.assertEqual(len(grants), 1)


@unittest.skipUnless(os.getenv("PACK_CREDIT_TEST_DATABASE_URL"), "requires PostgreSQL 16 test service")
class PostgreSQLMigrationSafetyTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        import psycopg

        cls.url = os.environ["PACK_CREDIT_TEST_DATABASE_URL"]
        _reset_postgres(cls.url, MIGRATIONS[:-1])
        with psycopg.connect(cls.url) as connection:
            user_id = uuid4()
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
            connection.execute("""
                insert into public.purchase(
                    user_id, stripe_checkout_session_id, status, currency, amount_cents, credits,
                    package_code, subtotal_cents, gst_cents, total_paid_cents, single_pack_price_cents
                ) values (%s, 'cs_unknown_mode', 'pending', 'AUD', 1695, 1,
                    'single', 1695, 0, 1695, 1695)
            """, (user_id,))

    def test_0903_refuses_to_guess_livemode_for_existing_rows(self):
        import psycopg

        migration = Path(__file__).resolve().parents[2] / "supabase" / "migrations" / MIGRATIONS[-1]
        with psycopg.connect(self.url) as connection:
            with self.assertRaisesRegex(psycopg.Error, "livemode"):
                connection.execute(migration.read_text(encoding="utf-8"))


@unittest.skipUnless(os.getenv("PACK_CREDIT_TEST_DATABASE_URL"), "requires PostgreSQL 16 test service")
class PostgreSQLPaymentOrderTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.url = os.environ["PACK_CREDIT_TEST_DATABASE_URL"]
        _reset_postgres(cls.url)

    def test_checkout_then_success_webhook_fills_payment_intent_once(self):
        import psycopg

        user_id = uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
            connection.execute("""
                insert into public.purchase(
                    user_id, stripe_checkout_session_id, status, currency, amount_cents, credits,
                    package_code, subtotal_cents, gst_cents, total_paid_cents, single_pack_price_cents,
                    gst_enabled, livemode, catalog_version
                ) values (%s, 'cs_checkout_success', 'pending', 'AUD', 1695, 1,
                    'single', 1695, 0, 1695, 1695, false, false, '2026-10-09')
            """, (user_id,))
            balance = connection.execute("""
                select public.process_stripe_purchase_event(
                    'evt_checkout_success', 'checkout.session.completed', 'fingerprint-1',
                    'cs_checkout_success', 'pi_first', %s, 'single', 1,
                    1695, 0, 1695, 1695, 'AUD', false, false, '2026-10-09'
                )
            """, (user_id,)).fetchone()[0]
            order = connection.execute("""
                select status, stripe_payment_intent_id from public.purchase
                where stripe_checkout_session_id = 'cs_checkout_success'
            """).fetchone()
            grants = connection.execute("""
                select count(*) from public.packcreditledger
                where stripe_checkout_session_id = 'cs_checkout_success'
                  and entry_type = 'grant_stripe_purchase'
            """).fetchone()[0]
        self.assertEqual(balance, 3)
        self.assertEqual(order, ("paid", "pi_first"))
        self.assertEqual(grants, 1)

    def test_required_0903_database_functions_exist(self):
        import psycopg

        signatures = (
            "public.process_stripe_purchase_event(text,text,text,text,text,uuid,text,integer,integer,integer,integer,integer,text,boolean,boolean,text)",
            "public.record_stripe_event_failure(text,text,text,text,text,boolean)",
            "public.record_stripe_event_observation(text,text,text,text,text,text,boolean,text)",
            "public.reserve_checkout_creation(uuid,text,text,timestamp with time zone)",
        )
        with psycopg.connect(self.url) as connection:
            found = [connection.execute("select to_regprocedure(%s)", (signature,)).fetchone()[0] for signature in signatures]
        self.assertTrue(all(found), found)

    def test_six_concurrent_checkout_requests_reserve_exactly_five(self):
        import psycopg

        user_id = uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))

        def reserve(index):
            with psycopg.connect(self.url) as connection:
                return connection.execute("""
                    select result from public.reserve_checkout_creation(%s, %s, 'single', now())
                """, (user_id, f"key-{index}")).fetchone()[0]

        with ThreadPoolExecutor(max_workers=6) as pool:
            results = list(pool.map(reserve, range(6)))
        self.assertEqual(results.count("reserved"), 5)
        self.assertEqual(results.count("rate_limited"), 1)

    def test_late_success_cannot_revive_refunded_order(self):
        import psycopg

        user_id = uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
            connection.execute("""
                insert into public.purchase(
                    user_id, stripe_checkout_session_id, stripe_payment_intent_id, status,
                    currency, amount_cents, credits, package_code, subtotal_cents, gst_cents,
                    total_paid_cents, single_pack_price_cents, gst_enabled, livemode, catalog_version
                ) values (%s, 'cs_refunded', 'pi_refunded', 'refunded',
                    'AUD', 1695, 1, 'single', 1695, 0, 1695, 1695, false, false, '2026-10-09')
            """, (user_id,))
            with self.assertRaises(psycopg.Error):
                connection.execute("""
                    select public.process_stripe_purchase_event(
                        'evt_late_success', 'checkout.session.completed', 'fingerprint-late',
                        'cs_refunded', 'pi_refunded', %s, 'single', 1,
                        1695, 0, 1695, 1695, 'AUD', false, false, '2026-10-09'
                    )
                """, (user_id,))
            root = Path(__file__).resolve().parents[2] / "supabase" / "migrations"
            for name in (
                "20260807_commercial_foundation.sql", "20261002_pack_credit_ledger.sql",
                "20261003080058_pack_credit_engine.sql", "20261003085650_pack_credit_column_defaults.sql",
                "20261003093309_custom_manual_pack_topup.sql", "2026100901_payment_orders_events.sql",
            ):
                connection.execute((root / name).read_text(encoding="utf-8"))

    def test_concurrent_duplicate_event_grants_once(self):
        import psycopg

        user_id = uuid4()
        facts = {
            "stripe_checkout_session_id": "cs_pg_concurrent", "stripe_payment_intent_id": "pi_pg_concurrent",
            "user_id": str(user_id), "package_code": "starter", "credits": 8,
            "subtotal_cents": 9995, "gst_cents": 1000, "total_paid_cents": 10995,
            "single_pack_price_cents": 1374, "currency": "AUD",
        }
        fingerprint = _event_fingerprint(facts)
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))

        def deliver():
            with psycopg.connect(self.url) as connection:
                return connection.execute("""
                    select public.process_stripe_purchase_event(
                        %s, %s, %s, %s, %s, %s, %s, %s,
                        %s, %s, %s, %s, %s, %s, %s, %s
                    )
                """, ("evt_pg_concurrent", "checkout.session.completed", fingerprint,
                      "cs_pg_concurrent", "pi_pg_concurrent", user_id, "starter", 8,
                      9995, 1000, 10995, 1374, "AUD", False, True, "2026-10-09")).fetchone()[0]

        with ThreadPoolExecutor(max_workers=2) as pool:
            balances = list(pool.map(lambda _: deliver(), range(2)))
        with psycopg.connect(self.url) as connection:
            grants = connection.execute("select count(*) from public.packcreditledger where entry_type='grant_stripe_purchase'").fetchone()[0]
            attempts = connection.execute("select status, attempt_count from public.stripeevent where stripe_event_id='evt_pg_concurrent'").fetchone()
        self.assertEqual(balances, [10, 10])
        self.assertEqual(grants, 1)
        self.assertEqual(attempts, ("processed", 1))

    def test_frontend_roles_cannot_read_payment_tables_or_execute_grants(self):
        import psycopg

        with psycopg.connect(self.url) as connection:
            table_acl = connection.execute(
                "select has_table_privilege('authenticated', 'public.purchase', 'select')"
            ).fetchone()[0]
            function_acl = connection.execute("""
                select has_function_privilege('authenticated',
                    'public.grant_manual_pack_topup(uuid,text,integer,integer,text,uuid,text)', 'execute')
            """).fetchone()[0]
        self.assertFalse(table_acl)
        self.assertFalse(function_acl)


if __name__ == "__main__":
    unittest.main()
