import os
import unittest
from datetime import datetime, timedelta, timezone
from pathlib import Path
from uuid import uuid4

from sqlalchemy.pool import NullPool
from sqlmodel import Session, create_engine

from app.pack_credits import expire_pack_reservations


ROOT = Path(__file__).resolve().parents[2]
MIGRATION = ROOT / "supabase" / "migrations" / "2026100902_credit_lots_refunds.sql"


class CreditLotMigrationContractTests(unittest.TestCase):
    def test_migration_defines_fifo_allocations_refunds_and_frontend_denial(self):
        sql = MIGRATION.read_text(encoding="utf-8").lower()
        for contract in (
            "create table if not exists public.packcreditlot",
            "create table if not exists public.packcreditallocation",
            "create table if not exists public.paymentrefund",
            "order by created_at, id",
            "alter table public.packcreditlot enable row level security",
            "revoke all on public.packcreditlot",
            "processing_lease_expires_at",
            "stripe_idempotency_key",
            "get_available_pack_credits",
        ):
            self.assertIn(contract, sql)

    def test_refund_storage_has_no_stripe_network_code(self):
        sql = MIGRATION.read_text(encoding="utf-8").lower()
        self.assertNotIn("api.stripe.com", sql)
        self.assertNotIn("http_", sql)


@unittest.skipUnless(os.getenv("PACK_CREDIT_TEST_DATABASE_URL"), "requires PostgreSQL 16 test service")
class PostgreSQLCreditLotTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        import psycopg

        cls.url = os.environ["PACK_CREDIT_TEST_DATABASE_URL"]
        with psycopg.connect(cls.url) as connection:
            if "test" not in connection.info.dbname.lower():
                raise RuntimeError("PACK_CREDIT_TEST_DATABASE_URL must identify a test database")
            connection.execute("drop schema if exists public cascade")
            connection.execute("drop schema if exists auth cascade")
            connection.execute("create schema public")
            connection.execute("create schema auth")
            connection.execute("create table auth.users (id uuid primary key)")
            connection.execute("create function auth.uid() returns uuid language sql stable as 'select null::uuid'")
            connection.execute("""
                create table public.generationusage (
                    id bigint generated by default as identity primary key,
                    user_id uuid not null, application_id integer, pack_id uuid not null,
                    generated_at timestamptz not null, completed_at timestamptz
                )
            """)
            migrations = ROOT / "supabase" / "migrations"
            for name in (
                "20260807_commercial_foundation.sql", "20261002_pack_credit_ledger.sql",
                "20261003080058_pack_credit_engine.sql", "20261003085650_pack_credit_column_defaults.sql",
                "20261003093309_custom_manual_pack_topup.sql", "2026100901_payment_orders_events.sql",
                "2026100902_credit_lots_refunds.sql",
            ):
                connection.execute((migrations / name).read_text(encoding="utf-8"))

    def test_fifo_exact_release_and_balance_invariant(self):
        import psycopg

        user_id, admin_id, first_pack, second_pack = uuid4(), uuid4(), uuid4(), uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s), (%s)", (user_id, admin_id))
            connection.execute(
                "select public.grant_manual_pack_topup(%s,'single',1,1695,'manual:fifo',%s,'test')",
                (user_id, admin_id),
            )
            self.assertEqual(connection.execute(
                "select result_status from public.reserve_pack_credits(%s,%s,2,500)", (user_id, first_pack)
            ).fetchone()[0], "reserved")
            self.assertTrue(connection.execute(
                "select public.complete_pack_credits(%s,%s)", (user_id, first_pack)
            ).fetchone()[0])
            self.assertEqual(connection.execute(
                "select result_status from public.reserve_pack_credits(%s,%s,1,500)", (user_id, second_pack)
            ).fetchone()[0], "reserved")
            self.assertTrue(connection.execute(
                "select public.release_pack_credits(%s,%s)", (user_id, second_pack)
            ).fetchone()[0])
            lots = connection.execute("""
                select source_type, granted_credits, remaining_credits, refundable
                from public.packcreditlot where user_id=%s order by created_at,id
            """, (user_id,)).fetchall()
            invariant = connection.execute("""
                select a.balance,
                    (select coalesce(sum(remaining_credits),0) from public.packcreditlot where user_id=a.user_id)
                    + (select coalesce(sum(credits),0) from public.packcreditallocation where user_id=a.user_id and status='reserved')
                from public.packcreditaccount a where user_id=%s
            """, (user_id,)).fetchone()
        self.assertEqual(lots, [("free", 2, 0, False), ("manual", 1, 1, False)])
        self.assertEqual(invariant, (1, 1))

    def test_active_reservation_uses_2a_balance_path_and_frontend_has_no_access(self):
        import psycopg

        user_id, pack_id = uuid4(), uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
            result = connection.execute(
                "select * from public.reserve_pack_credits(%s,%s,1,500)", (user_id, pack_id)
            ).fetchone()
            raw = connection.execute(
                "select balance from public.packcreditaccount where user_id=%s", (user_id,)
            ).fetchone()[0]
            available = connection.execute(
                "select public.get_available_pack_credits(%s)", (user_id,)
            ).fetchone()[0]
            refund_acl = connection.execute(
                "select has_table_privilege('authenticated','public.paymentrefund','select')"
            ).fetchone()[0]
        self.assertEqual(result, ("reserved", 1))
        self.assertEqual((raw, available), (2, 1))
        self.assertFalse(refund_acl)

    def test_crashed_expired_reservation_releases_and_preserves_balance_invariant(self):
        import psycopg

        user_id, pack_id = uuid4(), uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
            self.assertEqual(connection.execute(
                "select result_status from public.reserve_pack_credits(%s,%s,1,500)",
                (user_id, pack_id),
            ).fetchone()[0], "reserved")
            connection.execute(
                "update public.generationusage set expires_at=now()-interval '1 minute' where pack_id=%s",
                (pack_id,),
            )

        engine = create_engine(self.url, poolclass=NullPool)
        try:
            with Session(engine) as session:
                self.assertEqual(expire_pack_reservations(session, datetime.now(timezone.utc)), 1)
                session.commit()
        finally:
            engine.dispose()

        with psycopg.connect(self.url) as connection:
            state = connection.execute(
                "select status from public.generationusage where pack_id=%s", (pack_id,)
            ).fetchone()[0]
            invariant = connection.execute("""
                select a.balance,
                    (select coalesce(sum(remaining_credits),0) from public.packcreditlot where user_id=a.user_id)
                    + (select coalesce(sum(credits),0) from public.packcreditallocation
                       where user_id=a.user_id and status='reserved')
                from public.packcreditaccount a where user_id=%s
            """, (user_id,)).fetchone()
        self.assertEqual(state, "released")
        self.assertEqual(invariant, (2, 2))


if __name__ == "__main__":
    unittest.main()
