import os
import asyncio
import unittest
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta, timezone
from pathlib import Path
from tempfile import TemporaryDirectory
from types import SimpleNamespace
from unittest.mock import patch
from uuid import uuid4

from sqlalchemy.pool import NullPool
from sqlmodel import Session, SQLModel, create_engine, select

from app import database
from app.auth import AuthenticatedUser
from app.config import Settings, settings
from app.models import PackCreditAccount, PackCreditLedger, Purchase, StripeEvent
from app.pack_credits import _event_fingerprint, _payment_failure_reason, process_stripe_purchase_event
from app.payment_operations import ReplayRequest, failed_events, reconciliation, replay
from app.payments import STRIPE_API_VERSION, create_checkout_session, validate_stripe_settings


MIGRATIONS = (
    "20260807_commercial_foundation.sql", "20261002_pack_credit_ledger.sql",
    "20261003080058_pack_credit_engine.sql", "20261003085650_pack_credit_column_defaults.sql",
    "20261003093309_custom_manual_pack_topup.sql", "2026100901_payment_orders_events.sql",
    "2026100902_credit_lots_refunds.sql", "2026100903_stripe_checkout_webhook.sql",
)


def _reset_postgres(url, migrations=MIGRATIONS):
    import psycopg

    with psycopg.connect(url) as connection:
        if "test" not in connection.info.dbname.lower():
            raise RuntimeError("PACK_CREDIT_TEST_DATABASE_URL must identify a test database")
        connection.execute("drop schema if exists public cascade")
        connection.execute("drop schema if exists auth cascade")
        connection.execute("create schema public")
        connection.execute("create schema auth")
        connection.execute("create table auth.users (id uuid primary key)")
        connection.execute("create function auth.uid() returns uuid language sql stable as 'select null::uuid'")
        connection.execute("""
            create table public.generationusage (
                id bigint generated by default as identity primary key,
                user_id uuid not null, application_id integer, pack_id uuid not null,
                generated_at timestamptz not null, completed_at timestamptz
            )
        """)
        root = Path(__file__).resolve().parents[2] / "supabase" / "migrations"
        for name in migrations:
            connection.execute((root / name).read_text(encoding="utf-8"))


class PaymentEventTransactionTests(unittest.TestCase):
    def setUp(self):
        self.temp = TemporaryDirectory(dir=Path(__file__).parent)
        self.engine = create_engine(
            f"sqlite:///{Path(self.temp.name) / 'payments.db'}",
            connect_args={"check_same_thread": False},
            poolclass=NullPool,
        )
        SQLModel.metadata.create_all(self.engine)

    def tearDown(self):
        self.engine.dispose()
        self.temp.cleanup()

    def test_online_create_all_excludes_migration_only_payment_tables(self):
        with patch.object(settings, "deployment_mode", "online"):
            names = {table.name for table in database._create_all_tables()}
        self.assertTrue(database.MIGRATION_ONLY_TABLES.isdisjoint(names))

    def test_checkout_operational_schema_is_declared_but_never_created_at_startup(self):
        purchase_columns = set(Purchase.__table__.columns.keys())
        event_columns = set(StripeEvent.__table__.columns.keys())
        self.assertTrue({
            "livemode", "expires_at", "refund_detected_at",
            "checkout_idempotency_key_hash", "gst_enabled",
        }.issubset(purchase_columns))
        self.assertTrue({
            "livemode", "failure_reason_code", "stripe_object_id",
        }.issubset(event_columns))
        self.assertTrue({
            "paymentcheckoutrate", "paymentoperationaudit",
        }.issubset(database.MIGRATION_ONLY_TABLES))

    def test_failed_processing_rolls_back_records_failure_and_reraises_then_retries_once(self):
        user_id = uuid4()
        facts = dict(
            stripe_event_id="evt_retry_once",
            stripe_checkout_session_id="cs_retry_once",
            stripe_payment_intent_id="pi_retry_once",
            user_id=user_id,
            package_code="single",
            credits=1,
            subtotal_cents=1695,
            gst_cents=0,
            total_paid_cents=1695,
            single_pack_price_cents=1695,
            currency="AUD",
        )

        with Session(self.engine) as session, patch(
            "app.pack_credits._grant_pack_credits", side_effect=RuntimeError("transient database failure")
        ):
            with self.assertRaisesRegex(RuntimeError, "transient database failure"):
                process_stripe_purchase_event(session, **facts)

        with Session(self.engine) as session:
            event = session.get(StripeEvent, "evt_retry_once")
            self.assertEqual((event.status, event.attempt_count), ("failed", 1))
            self.assertIsNone(session.exec(select(Purchase)).first())
            self.assertIsNone(session.get(PackCreditAccount, user_id))

        with Session(self.engine) as session:
            first = process_stripe_purchase_event(session, **facts)
            repeated = process_stripe_purchase_event(session, **facts)

        with Session(self.engine) as session:
            event = session.get(StripeEvent, "evt_retry_once")
            grants = session.exec(select(PackCreditLedger).where(
                PackCreditLedger.entry_type == "grant_stripe_purchase"
            )).all()
            self.assertEqual((first, repeated), (3, 3))
            self.assertEqual((event.status, event.attempt_count), ("processed", 2))
            self.assertEqual(len(grants), 1)


@unittest.skipUnless(os.getenv("PACK_CREDIT_TEST_DATABASE_URL"), "requires PostgreSQL 16 test service")
class PostgreSQLMigrationSafetyTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        import psycopg

        cls.url = os.environ["PACK_CREDIT_TEST_DATABASE_URL"]
        _reset_postgres(cls.url, MIGRATIONS[:-1])
        with psycopg.connect(cls.url) as connection:
            user_id = uuid4()
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
            connection.execute("""
                insert into public.purchase(
                    user_id, stripe_checkout_session_id, status, currency, amount_cents, credits,
                    package_code, subtotal_cents, gst_cents, total_paid_cents, single_pack_price_cents
                ) values (%s, 'cs_unknown_mode', 'pending', 'AUD', 1695, 1,
                    'single', 1695, 0, 1695, 1695)
            """, (user_id,))

    def test_0903_refuses_to_guess_livemode_for_existing_rows(self):
        import psycopg

        migration = Path(__file__).resolve().parents[2] / "supabase" / "migrations" / MIGRATIONS[-1]
        with psycopg.connect(self.url) as connection:
            with self.assertRaisesRegex(psycopg.Error, "livemode"):
                connection.execute(migration.read_text(encoding="utf-8"))


@unittest.skipUnless(os.getenv("PACK_CREDIT_TEST_DATABASE_URL"), "requires PostgreSQL 16 test service")
class PostgreSQLPaymentOrderTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.url = os.environ["PACK_CREDIT_TEST_DATABASE_URL"]
        _reset_postgres(cls.url)

    def setUp(self):
        import psycopg

        with psycopg.connect(self.url) as connection:
            version = connection.execute("show server_version_num").fetchone()[0]
        self.assertTrue(version.startswith("16"), version)

    def _insert_observation_order(self, suffix, status="pending", dispute_status="none"):
        import psycopg

        user_id = uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
            order_id = connection.execute("""
                insert into public.purchase(
                    user_id,stripe_checkout_session_id,stripe_payment_intent_id,status,dispute_status,
                    currency,amount_cents,credits,package_code,subtotal_cents,gst_cents,
                    total_paid_cents,single_pack_price_cents,gst_enabled,livemode,catalog_version
                ) values (%s,%s,%s,%s,%s,'AUD',1695,1,'single',1695,0,1695,1695,false,false,'2026-10-09')
                returning id
            """, (user_id, f"cs_obs_{suffix}", f"pi_obs_{suffix}", status, dispute_status)).fetchone()[0]
        return order_id

    def _record_observation(self, suffix, action, matched=True):
        import psycopg

        session_id = f"cs_obs_{suffix}" if matched else f"cs_missing_{suffix}"
        payment_intent_id = f"pi_obs_{suffix}" if matched else f"pi_missing_{suffix}"
        with psycopg.connect(self.url) as connection:
            result = connection.execute("""
                select public.record_stripe_event_observation(
                    %s,%s,%s,%s,%s,%s,false,%s
                )
            """, (f"evt_obs_{suffix}", f"test.{action}", f"fp_{suffix}",
                  f"obj_{suffix}", session_id, payment_intent_id, action)).fetchone()[0]
            event = connection.execute("""
                select status,failure_reason_code from public.stripeevent where stripe_event_id=%s
            """, (f"evt_obs_{suffix}",)).fetchone()
            order = connection.execute("""
                select status,dispute_status,refund_detected_at is not null from public.purchase
                where stripe_checkout_session_id=%s
            """, (session_id,)).fetchone()
        return result, event, order

    def test_observation_payment_failed(self):
        self._insert_observation_order("payment_failed")
        result, event, order = self._record_observation("payment_failed", "payment_failed")
        self.assertEqual((result, event, order[0]), ("processed", ("processed", None), "failed"))

    def test_observation_expired(self):
        self._insert_observation_order("expired")
        result, event, order = self._record_observation("expired", "expired")
        self.assertEqual((result, event, order[0]), ("processed", ("processed", None), "cancelled"))

    def test_observation_refund_detected(self):
        self._insert_observation_order("refund", status="paid")
        result, event, order = self._record_observation("refund", "refund_detected")
        self.assertEqual((result, event, order[2]), ("observed_pending", ("observed_pending", None), True))

    def test_observation_dispute_pending(self):
        self._insert_observation_order("dispute_pending", status="paid")
        result, event, order = self._record_observation("dispute_pending", "dispute_pending")
        self.assertEqual((result, event, order[1]), ("observed_pending", ("observed_pending", None), "needs_review"))

    def test_observation_dispute_won(self):
        self._insert_observation_order("dispute_won", status="paid", dispute_status="needs_review")
        result, event, order = self._record_observation("dispute_won", "dispute_won")
        self.assertEqual((result, event, order[1]), ("observed_pending", ("observed_pending", None), "won"))

    def test_observation_dispute_lost(self):
        self._insert_observation_order("dispute_lost", status="paid", dispute_status="needs_review")
        result, event, order = self._record_observation("dispute_lost", "dispute_lost")
        self.assertEqual((result, event, order[1]), ("observed_pending", ("observed_pending", None), "lost"))

    def test_observation_unmatched_order_records_failure(self):
        result, event, order = self._record_observation("unmatched", "refund_detected", matched=False)
        self.assertEqual((result, event, order), ("failed", ("failed", "order_not_found"), None))

    def test_terminal_order_async_failure_is_order_state_conflict(self):
        self._insert_observation_order("terminal", status="paid")
        result, event, order = self._record_observation("terminal", "payment_failed")
        self.assertEqual((result, event, order[0]), ("failed", ("failed", "order_state_conflict"), "paid"))

    def test_duplicate_terminal_observations_are_idempotently_processed(self):
        cases = (
            ("failed_duplicate", "failed", "none", "payment_failed", "processed"),
            ("expired_duplicate", "cancelled", "none", "expired", "processed"),
            ("won_duplicate", "paid", "won", "dispute_won", "observed_pending"),
            ("lost_duplicate", "paid", "lost", "dispute_lost", "observed_pending"),
        )
        for suffix, status, dispute_status, action, expected in cases:
            with self.subTest(action=action):
                self._insert_observation_order(suffix, status=status, dispute_status=dispute_status)
                result, event, _ = self._record_observation(suffix, action)
                self.assertEqual((result, event), (expected, (expected, None)))

    def test_dispute_status_never_moves_backward(self):
        self._insert_observation_order("late_dispute", status="paid", dispute_status="lost")
        result, event, order = self._record_observation("late_dispute", "dispute_pending")
        self.assertEqual((result, event, order[1]), ("observed_pending", ("observed_pending", None), "lost"))

    def test_failure_recorder_preserves_processed_and_observed_events(self):
        import psycopg

        with psycopg.connect(self.url) as connection:
            for suffix, status in (("processed", "processed"), ("observed", "observed_pending")):
                connection.execute("""
                    insert into public.stripeevent(stripe_event_id,event_type,facts_fingerprint,status,
                        attempt_count,livemode) values (%s,'test.event',%s,%s,1,false)
                """, (f"evt_keep_{suffix}", f"fp_keep_{suffix}", status))
                connection.execute("""
                    select public.record_stripe_event_failure(%s,'test.event',%s,'late_error','late',false)
                """, (f"evt_keep_{suffix}", f"fp_keep_{suffix}"))
            rows = connection.execute("""
                select stripe_event_id,status,failure_reason_code from public.stripeevent
                where stripe_event_id like 'evt_keep_%' order by stripe_event_id
            """).fetchall()
        self.assertEqual(rows, [
            ("evt_keep_observed", "observed_pending", None),
            ("evt_keep_processed", "processed", None),
        ])

    def test_released_key_reentry_and_new_key_share_five_slot_lock(self):
        import psycopg

        user_id = uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
            for index in range(4):
                connection.execute("""
                    insert into public.paymentcheckoutrate(user_id,idempotency_key_hash,package_code,status)
                    values (%s,%s,'single','reserved')
                """, (user_id, f"active-{index}"))
            connection.execute("""
                insert into public.paymentcheckoutrate(user_id,idempotency_key_hash,package_code,status,released_at)
                values (%s,'released-key','single','released',now())
            """, (user_id,))

        def reserve(key):
            with psycopg.connect(self.url) as connection:
                return connection.execute(
                    "select result from public.reserve_checkout_creation(%s,%s,'single')", (user_id, key)
                ).fetchone()[0]

        with ThreadPoolExecutor(max_workers=2) as pool:
            results = list(pool.map(reserve, ("released-key", "new-key")))
        self.assertEqual(sorted(results), ["rate_limited", "reserved"])

    def test_account_delete_is_blocked_and_financial_rows_are_retained(self):
        import psycopg

        user_id = uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
            purchase_id = connection.execute("""
                insert into public.purchase(user_id,stripe_checkout_session_id,status,currency,amount_cents,
                    credits,package_code,subtotal_cents,gst_cents,total_paid_cents,single_pack_price_cents,
                    gst_enabled,livemode,catalog_version)
                values (%s,'cs_delete','paid','AUD',1695,1,'single',1695,0,1695,1695,false,false,'2026-10-09') returning id
            """, (user_id,)).fetchone()[0]
            connection.execute("""
                insert into public.paymentrefund(user_id,purchase_id,status,currency,requested_amount_cents,
                    stripe_idempotency_key) values (%s,%s,'requested','AUD',1695,'refund-delete')
            """, (user_id, purchase_id))
            connection.execute("""
                insert into public.paymentoperationaudit(admin_user_id,operation,target_type,target_id,result)
                values (%s,'test','purchase',%s,'created')
            """, (user_id, str(purchase_id)))
            connection.commit()
            with self.assertRaises(psycopg.errors.ForeignKeyViolation):
                connection.execute("delete from auth.users where id=%s", (user_id,))
            connection.rollback()
            counts = connection.execute("""
                select
                  (select count(*) from public.purchase where user_id=%s),
                  (select count(*) from public.paymentrefund where user_id=%s),
                  (select count(*) from public.paymentoperationaudit where admin_user_id=%s)
            """, (user_id, user_id, user_id)).fetchone()
        self.assertEqual(counts, (1, 1, 1))

    def test_checkout_then_success_webhook_fills_payment_intent_once(self):
        import psycopg

        user_id = uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
            connection.execute("""
                insert into public.purchase(
                    user_id, stripe_checkout_session_id, status, currency, amount_cents, credits,
                    package_code, subtotal_cents, gst_cents, total_paid_cents, single_pack_price_cents,
                    gst_enabled, livemode, catalog_version
                ) values (%s, 'cs_checkout_success', 'pending', 'AUD', 1695, 1,
                    'single', 1695, 0, 1695, 1695, false, false, '2026-10-09')
            """, (user_id,))
            balance = connection.execute("""
                select public.process_stripe_purchase_event(
                    'evt_checkout_success', 'checkout.session.completed', 'fingerprint-1',
                    'cs_checkout_success', 'pi_first', %s, 'single', 1,
                    1695, 0, 1695, 1695, 'AUD', false, false, '2026-10-09'
                )
            """, (user_id,)).fetchone()[0]
            order = connection.execute("""
                select status, stripe_payment_intent_id from public.purchase
                where stripe_checkout_session_id = 'cs_checkout_success'
            """).fetchone()
            grants = connection.execute("""
                select count(*) from public.packcreditledger l join public.purchase p on p.id = l.purchase_id
                where p.stripe_checkout_session_id = 'cs_checkout_success'
                  and l.entry_type = 'grant_stripe_purchase'
            """).fetchone()[0]
        self.assertEqual(balance, 3)
        self.assertEqual(order, ("paid", "pi_first"))
        self.assertEqual(grants, 1)

    def test_admin_failure_paging_filters_and_reconciliation_categories(self):
        import psycopg

        user_id = uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
        engine = create_engine(self.url, poolclass=NullPool)
        try:
            with Session(engine) as session:
                expired = Purchase(
                    user_id=user_id, stripe_checkout_session_id="cs_report_expired", status="pending",
                    package_code="single", currency="AUD", credits=1, amount_cents=1695,
                    subtotal_cents=1695, gst_cents=0, total_paid_cents=1695,
                    single_pack_price_cents=1695, expires_at=datetime.now(timezone.utc) - timedelta(seconds=1),
                )
                session.add(expired)
                session.add_all([
                    StripeEvent(stripe_event_id="evt_report_failed", event_type="checkout.session.completed",
                                facts_fingerprint="a", status="failed", attempt_count=1),
                    StripeEvent(stripe_event_id="evt_report_observed", event_type="charge.refunded",
                                facts_fingerprint="b", status="observed_pending", attempt_count=1),
                    StripeEvent(stripe_event_id="evt_report_orphan", event_type="checkout.session.completed",
                                facts_fingerprint="c", status="processed", attempt_count=1),
                ])
                session.commit()
                expired_id = expired.id
                page = failed_events(session, status="failed", limit=1)
                report = reconciliation(session)
            self.assertEqual([item["stripe_event_id"] for item in page["items"]], ["evt_report_failed"])
            self.assertIn("evt_report_orphan", report["processed_event_without_order_ids"])
            self.assertIn(expired_id, report["expired_pending_order_ids"])
        finally:
            engine.dispose()

    def test_stream_limit_and_unified_stripe_configuration_contracts(self):
        from app.main import stripe_webhook

        class StreamingRequest:
            headers = {}

            async def stream(self):
                yield b"x" * (200 * 1024)
                yield b"y" * (100 * 1024)

        engine = create_engine(self.url, poolclass=NullPool)
        try:
            with Session(engine) as session:
                with self.assertRaisesRegex(Exception, "too large"):
                    asyncio.run(stripe_webhook(StreamingRequest(), session))
        finally:
            engine.dispose()
        validate_stripe_settings(Settings(_env_file=None, stripe_api_version=STRIPE_API_VERSION))
        with self.assertRaisesRegex(ValueError, "STRIPE_API_VERSION"):
            validate_stripe_settings(Settings(_env_file=None, stripe_api_version="wrong"))

    def test_transient_failure_reason_codes_are_never_empty(self):
        class DatabaseUnavailable(Exception):
            sqlstate = "08006"

        class LockTimeout(Exception):
            sqlstate = "55P03"

        self.assertEqual(_payment_failure_reason(DatabaseUnavailable()), "database_unavailable")
        self.assertEqual(_payment_failure_reason(LockTimeout()), "lock_timeout")
        self.assertEqual(_payment_failure_reason(RuntimeError()), "internal_error")

    def test_replay_rejects_refund_events_before_credit_processing(self):
        gateway = SimpleNamespace(retrieve_event=lambda _id: {
            "id": "evt_refund_replay", "type": "charge.refunded", "livemode": False,
            "data": {"object": {"id": "ch_replay"}},
        })
        engine = create_engine(self.url, poolclass=NullPool)
        try:
            with Session(engine) as session:
                with self.assertRaisesRegex(ValueError, "successful Checkout"):
                    replay(session, gateway, uuid4(), ReplayRequest(stripe_event_id="evt_refund_replay"))
        finally:
            engine.dispose()

    def test_required_0903_database_functions_exist(self):
        import psycopg

        signatures = (
            "public.process_stripe_purchase_event(text,text,text,text,text,uuid,text,integer,integer,integer,integer,integer,text,boolean,boolean,text)",
            "public.record_stripe_event_failure(text,text,text,text,text,boolean)",
            "public.record_stripe_event_observation(text,text,text,text,text,text,boolean,text)",
            "public.reserve_checkout_creation(uuid,text,text)",
        )
        with psycopg.connect(self.url) as connection:
            found = [connection.execute("select to_regprocedure(%s)", (signature,)).fetchone()[0] for signature in signatures]
        self.assertTrue(all(found), found)

    def test_unified_preflight_is_read_only_and_returns_one_result_set(self):
        import psycopg

        script = Path(__file__).resolve().parents[2] / "supabase" / "diagnostics" / "payment_preflight.sql"
        sql = script.read_text(encoding="utf-8")
        self.assertNotIn("begin", sql.lower())
        self.assertNotIn("rollback", sql.lower())
        self.assertEqual(sql.count(";"), 1)
        with psycopg.connect(self.url) as connection:
            cursor = connection.cursor()
            cursor.execute(sql)
            result_sets, columns = [], []
            while True:
                if cursor.description:
                    columns = [column.name for column in cursor.description]
                    result_sets.append(cursor.fetchall())
                if not cursor.nextset():
                    break
        self.assertEqual(len(result_sets), 1)
        self.assertEqual(columns, ["check_name", "severity", "issue_count", "result"])
        names = {row[0] for row in result_sets[0]}
        self.assertIn("pre_2b_exact_balance_mismatch", names)
        self.assertIn("post_2b_balance_lot_reservation_mismatch", names)
        self.assertFalse(any(name.startswith("database_role:") for name in names))

    def test_backup_copies_all_five_tables_and_compares_live_counts(self):
        import psycopg

        script = Path(__file__).resolve().parents[2] / "supabase" / "operations" / "payment_backup_and_restore.sql"
        with psycopg.connect(self.url) as connection:
            cursor = connection.cursor()
            cursor.execute(script.read_text(encoding="utf-8"))
            result_sets = []
            while True:
                if cursor.description:
                    result_sets.append(cursor.fetchall())
                if not cursor.nextset():
                    break
        comparisons = result_sets[-1]
        self.assertEqual({row[0] for row in comparisons}, {
            "packcreditaccount", "packcreditledger", "generationusage", "purchase", "globalmonthlyusage",
        })
        self.assertTrue(all(live == backup and result == "MATCH" for _, live, backup, result in comparisons), comparisons)

    def test_six_concurrent_checkout_requests_reserve_exactly_five(self):
        import psycopg

        user_id = uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))

        def reserve(index):
            with psycopg.connect(self.url) as connection:
                return connection.execute("""
                    select result from public.reserve_checkout_creation(%s, %s, 'single')
                """, (user_id, f"key-{index}")).fetchone()[0]

        with ThreadPoolExecutor(max_workers=6) as pool:
            results = list(pool.map(reserve, range(6)))
        self.assertEqual(results.count("reserved"), 5)
        self.assertEqual(results.count("rate_limited"), 1)

    def test_late_success_cannot_revive_refunded_order(self):
        import psycopg

        user_id = uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
            connection.execute("""
                insert into public.purchase(
                    user_id, stripe_checkout_session_id, stripe_payment_intent_id, status,
                    currency, amount_cents, credits, package_code, subtotal_cents, gst_cents,
                    total_paid_cents, single_pack_price_cents, gst_enabled, livemode, catalog_version
                ) values (%s, 'cs_refunded', 'pi_refunded', 'refunded',
                    'AUD', 1695, 1, 'single', 1695, 0, 1695, 1695, false, false, '2026-10-09')
            """, (user_id,))
            with self.assertRaises(psycopg.Error):
                connection.execute("""
                    select public.process_stripe_purchase_event(
                        'evt_late_success', 'checkout.session.completed', 'fingerprint-late',
                        'cs_refunded', 'pi_refunded', %s, 'single', 1,
                        1695, 0, 1695, 1695, 'AUD', false, false, '2026-10-09'
                    )
                """, (user_id,))

    def test_retry_after_local_persistence_failure_recovers_same_stripe_session(self):
        import psycopg

        user_id = uuid4()
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))
        identity = AuthenticatedUser(user_id, "buyer@example.test")
        remote = SimpleNamespace(id="cs_recovered", url="https://stripe.test/recovered", livemode=False)
        gateway = unittest.mock.Mock()
        gateway.create_checkout_session.return_value = remote
        engine = create_engine(self.url, poolclass=NullPool)
        try:
            with Session(engine) as session:
                real_commit = session.commit
                commits = 0

                def fail_second_commit():
                    nonlocal commits
                    commits += 1
                    if commits == 2:
                        raise RuntimeError("simulated local persistence failure")
                    real_commit()

                with patch.object(session, "commit", side_effect=fail_second_commit):
                    with self.assertRaisesRegex(RuntimeError, "persistence"):
                        create_checkout_session(session, gateway, identity, "single", "retry-key")
            with Session(engine) as session:
                response = create_checkout_session(session, gateway, identity, "single", "retry-key")
                order = session.exec(select(Purchase).where(
                    Purchase.stripe_checkout_session_id == "cs_recovered"
                )).one()
            self.assertEqual(response.checkout_session_id, "cs_recovered")
            self.assertEqual(order.status, "pending")
            self.assertEqual(gateway.create_checkout_session.call_count, 2)
            keys = [call.args[1] for call in gateway.create_checkout_session.call_args_list]
            self.assertEqual(keys[0], keys[1])
        finally:
            engine.dispose()

    def test_concurrent_duplicate_event_grants_once(self):
        import psycopg

        user_id = uuid4()
        facts = {
            "stripe_checkout_session_id": "cs_pg_concurrent", "stripe_payment_intent_id": "pi_pg_concurrent",
            "user_id": str(user_id), "package_code": "starter", "credits": 8,
            "subtotal_cents": 10995, "gst_cents": 0, "total_paid_cents": 10995,
            "single_pack_price_cents": 1695, "currency": "AUD",
        }
        fingerprint = _event_fingerprint(facts)
        with psycopg.connect(self.url) as connection:
            connection.execute("insert into auth.users(id) values (%s)", (user_id,))

        def deliver():
            with psycopg.connect(self.url) as connection:
                return connection.execute("""
                    select public.process_stripe_purchase_event(
                        %s, %s, %s, %s, %s, %s, %s, %s,
                        %s, %s, %s, %s, %s, %s, %s, %s
                    )
                """, ("evt_pg_concurrent", "checkout.session.completed", fingerprint,
                      "cs_pg_concurrent", "pi_pg_concurrent", user_id, "starter", 8,
                      10995, 0, 10995, 1695, "AUD", False, False, "2026-10-09")).fetchone()[0]

        with ThreadPoolExecutor(max_workers=2) as pool:
            balances = list(pool.map(lambda _: deliver(), range(2)))
        with psycopg.connect(self.url) as connection:
            grants = connection.execute("""
                select count(*) from public.packcreditledger l join public.purchase p on p.id = l.purchase_id
                where l.entry_type = 'grant_stripe_purchase'
                  and p.stripe_checkout_session_id = 'cs_pg_concurrent'
            """).fetchone()[0]
            attempts = connection.execute("select status, attempt_count from public.stripeevent where stripe_event_id='evt_pg_concurrent'").fetchone()
        self.assertEqual(balances, [10, 10])
        self.assertEqual(grants, 1)
        self.assertEqual(attempts, ("processed", 1))

    def test_frontend_roles_cannot_read_payment_tables_or_execute_grants(self):
        import psycopg

        with psycopg.connect(self.url) as connection:
            table_acl = connection.execute(
                "select has_table_privilege('authenticated', 'public.purchase', 'select')"
            ).fetchone()[0]
            function_acl = connection.execute("""
                select has_function_privilege('authenticated',
                    'public.grant_manual_pack_topup(uuid,text,integer,integer,text,uuid,text)', 'execute')
            """).fetchone()[0]
            sequence_acl = connection.execute(
                "select has_sequence_privilege('authenticated','public.paymentcheckoutrate_id_seq','usage')"
            ).fetchone()[0]
        self.assertFalse(table_acl)
        self.assertFalse(function_acl)
        self.assertFalse(sequence_acl)

    def test_service_role_has_all_payment_table_and_sequence_permissions(self):
        import psycopg

        with psycopg.connect(self.url) as connection:
            table_permissions = connection.execute("""
                select table_name, has_table_privilege('service_role', 'public.' || table_name,
                    'select,insert,update,delete')
                from (values ('packcreditlot'),('packcreditallocation'),('paymentrefund')) t(table_name)
            """).fetchall()
            sequence_permissions = connection.execute("""
                select sequence_name, has_sequence_privilege('service_role', 'public.' || sequence_name,
                    'usage,select')
                from (values ('packcreditlot_id_seq'),('packcreditallocation_id_seq'),
                    ('paymentrefund_id_seq')) s(sequence_name)
            """).fetchall()
        self.assertTrue(all(allowed for _, allowed in table_permissions), table_permissions)
        self.assertTrue(all(allowed for _, allowed in sequence_permissions), sequence_permissions)

    def test_application_privilege_self_check_covers_payment_dependencies(self):
        from app.payment_operations import backend_privilege_check

        engine = create_engine(self.url, poolclass=NullPool)
        try:
            with Session(engine) as session:
                result = backend_privilege_check(session)
        finally:
            engine.dispose()
        self.assertTrue(result["ready"], result)
        checked = {item["name"] for item in result["checks"]}
        self.assertTrue({
            "globalmonthlyusage", "packcreditaccount", "packcreditledger", "generationusage",
            "packcreditlot", "packcreditallocation", "paymentrefund",
            "process_stripe_purchase_event", "record_stripe_event_failure",
            "record_stripe_event_observation", "reserve_checkout_creation",
        }.issubset(checked), checked)


if __name__ == "__main__":
    unittest.main()
