-- Source provenance for advertisements and explicitly referenced application attachments.

create table if not exists public.jobsource (
    id bigint generated by default as identity primary key,
    schema_version text not null default '1.0',
    source_id text not null unique,
    application_id bigint not null,
    user_id uuid not null references auth.users(id) on delete cascade,
    source_type text not null check (source_type in ('primary_advertisement', 'job_description_attachment', 'application_instruction_attachment', 'mandatory_form', 'other_supporting_attachment', 'unknown_attachment')),
    title text not null,
    label text not null,
    source_url text,
    discovered_from_source_id text,
    discovered_from_url text,
    content_type text,
    filename text,
    acquisition_status text not null check (acquisition_status in ('discovered', 'fetched', 'uploaded', 'unavailable', 'failed', 'requires_auth', 'unsupported')),
    extraction_status text not null check (extraction_status in ('not_attempted', 'extracted', 'partial', 'failed', 'not_applicable')),
    extracted_text text not null default '',
    content_sha256 text,
    canonical_url_hash text,
    classification_confidence text not null check (classification_confidence in ('high', 'medium', 'low')),
    classification_reasons_json text not null default '[]',
    warnings_json text not null default '[]',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    foreign key (application_id, user_id) references public.jobapplication(id, user_id) on delete cascade
);

create index if not exists jobsource_application_id_idx on public.jobsource(application_id);
create index if not exists jobsource_user_id_idx on public.jobsource(user_id);

alter table public.jobsource enable row level security;
drop policy if exists "jobsource_owner_all" on public.jobsource;
create policy "jobsource_owner_all" on public.jobsource
    for all to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.jobsource to authenticated;
grant usage, select on all sequences in schema public to authenticated;
