-- Job Application Assistant: invitation-only online beta schema
-- Run this only in the new, empty job-application-assistant-beta project.

create table if not exists public.applicantprofile (
    id bigint generated by default as identity primary key,
    user_id uuid not null unique references auth.users(id) on delete cascade,
    title text,
    first_name text not null,
    last_name text not null,
    preferred_name text,
    phone text not null,
    email text not null,
    postal_address text,
    suburb text,
    state text not null default 'WA',
    postcode text,
    country text not null default 'Australia',
    work_rights text not null default 'permanent_resident',
    availability_notice text not null default 'not_specified',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, user_id)
);

create table if not exists public.referee (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    profile_id bigint not null,
    display_order integer not null check (display_order between 1 and 2),
    organisation text not null,
    name text not null,
    position_title text not null,
    phone text not null,
    relationship text not null,
    email text not null,
    postal_address text,
    suburb text,
    state text not null default 'WA',
    postcode text,
    country text not null default 'Australia',
    unique (user_id, display_order),
    foreign key (profile_id, user_id) references public.applicantprofile(id, user_id) on delete cascade
);

create table if not exists public.resume (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    title text not null default 'Master Resume',
    source_text text not null,
    experiences_json text not null default '[]',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, user_id)
);

create table if not exists public.jobapplication (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    company text not null,
    position_title text not null,
    job_url text,
    job_description text not null,
    selection_criteria text,
    deadline date,
    status text not null default 'draft' check (status in ('draft', 'ready_to_apply', 'applied')),
    submission_reference text,
    submitted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, user_id)
);

create table if not exists public.generateddocument (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    application_id bigint not null,
    document_type text not null check (document_type in ('tailored_resume', 'cover_letter', 'selection_criteria', 'ats_analysis')),
    content text not null,
    used_experiences_json text not null default '[]',
    closing_styles_json text not null default '[]',
    created_at timestamptz not null default now(),
    foreign key (application_id, user_id) references public.jobapplication(id, user_id) on delete cascade
);

create table if not exists public.generationusage (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    application_id bigint,
    pack_id uuid not null,
    generated_at timestamptz not null default now()
);

create index if not exists resume_user_id_idx on public.resume(user_id);
create index if not exists referee_user_id_idx on public.referee(user_id);
create index if not exists jobapplication_user_id_idx on public.jobapplication(user_id);
create index if not exists generateddocument_user_id_idx on public.generateddocument(user_id);
create index if not exists generateddocument_application_id_idx on public.generateddocument(application_id);
create index if not exists generationusage_user_generated_idx on public.generationusage(user_id, generated_at);
create unique index if not exists generationusage_user_pack_idx on public.generationusage(user_id, pack_id);

-- Safe upgrades for beta databases created before structured experience capture.
alter table public.resume add column if not exists experiences_json text not null default '[]';
alter table public.generateddocument add column if not exists used_experiences_json text not null default '[]';
alter table public.generateddocument add column if not exists closing_styles_json text not null default '[]';

alter table public.applicantprofile enable row level security;
alter table public.referee enable row level security;
alter table public.resume enable row level security;
alter table public.jobapplication enable row level security;
alter table public.generateddocument enable row level security;
alter table public.generationusage enable row level security;

drop policy if exists "profile_owner_all" on public.applicantprofile;
create policy "profile_owner_all" on public.applicantprofile
    for all to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

drop policy if exists "referee_owner_all" on public.referee;
create policy "referee_owner_all" on public.referee
    for all to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

drop policy if exists "resume_owner_all" on public.resume;
create policy "resume_owner_all" on public.resume
    for all to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

drop policy if exists "application_owner_all" on public.jobapplication;
create policy "application_owner_all" on public.jobapplication
    for all to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

drop policy if exists "document_owner_all" on public.generateddocument;
create policy "document_owner_all" on public.generateddocument
    for all to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

-- Usage records are readable by their owner but are inserted by the backend only.
drop policy if exists "usage_owner_read" on public.generationusage;
create policy "usage_owner_read" on public.generationusage
    for select to authenticated
    using ((select auth.uid()) = user_id);

-- Prevent accidental broad grants. The authenticated role still needs table
-- privileges before RLS policies can permit a user's own rows.
grant select, insert, update, delete on public.applicantprofile to authenticated;
grant select, insert, update, delete on public.referee to authenticated;
grant select, insert, update, delete on public.resume to authenticated;
grant select, insert, update, delete on public.jobapplication to authenticated;
grant select, insert, update, delete on public.generateddocument to authenticated;
grant select on public.generationusage to authenticated;
grant usage, select on all sequences in schema public to authenticated;
