-- Pack credit storage only. Prices validate manual grants; no payment provider is connected.

create table if not exists public.packcreditaccount (
    user_id uuid primary key references auth.users(id) on delete cascade,
    balance integer not null default 0 check (balance >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.packcreditledger (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    entry_type text not null check (entry_type in ('grant_free', 'grant_manual_topup', 'debit_generation', 'release')),
    credits_delta integer not null check (credits_delta <> 0),
    pack_id uuid,
    package_code text check (package_code is null or package_code in ('single', 'starter', 'job_search', 'custom')),
    amount_cents integer check (amount_cents is null or amount_cents >= 0),
    currency text not null default 'AUD' check (currency = 'AUD'),
    note text,
    idempotency_key text not null unique,
    created_by_user_id uuid references auth.users(id),
    created_at timestamptz not null default now(),
    check (
        (entry_type in ('grant_free', 'grant_manual_topup', 'release') and credits_delta > 0)
        or (entry_type = 'debit_generation' and credits_delta < 0)
    )
);

create index if not exists packcreditledger_user_created_idx
    on public.packcreditledger(user_id, created_at);
create unique index if not exists packcreditledger_user_pack_entry_idx
    on public.packcreditledger(user_id, pack_id, entry_type)
    where pack_id is not null and entry_type in ('debit_generation', 'release');

create table if not exists public.globalmonthlyusage (
    month_start date primary key,
    reserved_count integer not null default 0 check (reserved_count >= 0),
    completed_count integer not null default 0 check (completed_count >= 0),
    updated_at timestamptz not null default now()
);

-- Beta history is free: every existing user starts with two lifetime credits.
insert into public.packcreditaccount (user_id, balance)
select id, 2 from auth.users
on conflict (user_id) do nothing;

insert into public.packcreditledger (
    user_id, entry_type, credits_delta, idempotency_key, note
)
select id, 'grant_free', 2, 'grant-free:' || id::text, 'Initial lifetime credits'
from auth.users
on conflict (idempotency_key) do nothing;

alter table public.generationusage add column if not exists status text;
alter table public.generationusage add column if not exists credit_cost integer;
alter table public.generationusage add column if not exists reserved_at timestamptz;
alter table public.generationusage add column if not exists expires_at timestamptz;
alter table public.generationusage add column if not exists released_at timestamptz;
alter table public.generationusage add column if not exists usage_month date;

update public.generationusage
set status = case
        when completed_at is not null then 'completed'
        when completed_at is null then 'released'
    end,
    credit_cost = coalesce(credit_cost, 1),
    reserved_at = coalesce(reserved_at, generated_at),
    released_at = case when completed_at is null then coalesce(released_at, generated_at) else released_at end,
    usage_month = coalesce(usage_month, date_trunc('month', generated_at at time zone 'UTC')::date)
where status is null;

alter table public.generationusage alter column status set default 'reserved';
alter table public.generationusage alter column status set not null;
alter table public.generationusage alter column credit_cost set default 1;
alter table public.generationusage alter column credit_cost set not null;
alter table public.generationusage alter column reserved_at set default now();
alter table public.generationusage alter column reserved_at set not null;
alter table public.generationusage alter column usage_month set default date_trunc('month', timezone('UTC', now()))::date;
alter table public.generationusage alter column usage_month set not null;
alter table public.generationusage drop constraint if exists generationusage_status_check;
alter table public.generationusage add constraint generationusage_status_check
    check (status in ('reserved', 'completed', 'released'));
alter table public.generationusage drop constraint if exists generationusage_credit_cost_check;
alter table public.generationusage add constraint generationusage_credit_cost_check
    check (credit_cost in (1, 2));

create index if not exists generationusage_month_status_idx
    on public.generationusage(usage_month, status);

alter table public.packcreditaccount enable row level security;
alter table public.packcreditledger enable row level security;
alter table public.globalmonthlyusage enable row level security;

drop policy if exists "pack_credit_account_owner_read" on public.packcreditaccount;
create policy "pack_credit_account_owner_read" on public.packcreditaccount
    for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "pack_credit_ledger_owner_read" on public.packcreditledger;
create policy "pack_credit_ledger_owner_read" on public.packcreditledger
    for select to authenticated using ((select auth.uid()) = user_id);

grant select on public.packcreditaccount to authenticated;
grant select on public.packcreditledger to authenticated;

comment on table public.packcreditledger is
    'Immutable Pack credit audit ledger. Manual top-up metadata does not confirm or process payment.';
