-- Commercial foundation. These tables do not enable charging by themselves.
-- Payment and credit writes must be performed by the trusted backend only.

create table if not exists public.creditledger (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    delta integer not null check (delta <> 0),
    reason text not null check (reason in ('trial', 'purchase', 'generation', 'generation_refund', 'referral', 'admin_adjustment', 'payment_refund')),
    reference_id text,
    idempotency_key text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists public.purchase (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    stripe_checkout_session_id text not null unique,
    stripe_payment_intent_id text unique,
    status text not null check (status in ('pending', 'paid', 'refunded', 'failed', 'cancelled')),
    currency text not null default 'aud' check (currency = 'aud'),
    amount_cents integer not null check (amount_cents > 0),
    credits integer not null check (credits > 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.referral (
    id bigint generated by default as identity primary key,
    inviter_user_id uuid not null references auth.users(id) on delete cascade,
    invited_user_id uuid not null unique references auth.users(id) on delete cascade,
    status text not null default 'pending' check (status in ('pending', 'earned', 'rejected')),
    reward_credits integer not null default 1 check (reward_credits = 1),
    created_at timestamptz not null default now(),
    earned_at timestamptz,
    check (inviter_user_id <> invited_user_id)
);

create index if not exists creditledger_user_created_idx on public.creditledger(user_id, created_at);
create index if not exists purchase_user_created_idx on public.purchase(user_id, created_at);
create index if not exists referral_inviter_status_idx on public.referral(inviter_user_id, status);

alter table public.creditledger enable row level security;
alter table public.purchase enable row level security;
alter table public.referral enable row level security;

drop policy if exists "credit_owner_read" on public.creditledger;
create policy "credit_owner_read" on public.creditledger for select to authenticated
    using ((select auth.uid()) = user_id);

drop policy if exists "purchase_owner_read" on public.purchase;
create policy "purchase_owner_read" on public.purchase for select to authenticated
    using ((select auth.uid()) = user_id);

drop policy if exists "referral_participant_read" on public.referral;
create policy "referral_participant_read" on public.referral for select to authenticated
    using ((select auth.uid()) = inviter_user_id or (select auth.uid()) = invited_user_id);

grant select on public.creditledger to authenticated;
grant select on public.purchase to authenticated;
grant select on public.referral to authenticated;

comment on table public.creditledger is 'Immutable credit balance ledger. Balance is the sum of delta for a user.';
comment on table public.purchase is 'Stripe purchase records written idempotently by trusted webhook handling.';
comment on table public.referral is 'One reward for the inviter after the invited user qualifies.';
