begin;

lock table public.purchase, public.stripeevent in share row exclusive mode;

alter table public.purchase
    add column if not exists gst_enabled boolean not null default false,
    add column if not exists livemode boolean not null default false,
    add column if not exists expires_at timestamptz,
    add column if not exists refund_detected_at timestamptz,
    add column if not exists checkout_idempotency_key_hash text;

create unique index if not exists purchase_user_checkout_key_key
    on public.purchase(user_id, checkout_idempotency_key_hash)
    where checkout_idempotency_key_hash is not null;

alter table public.stripeevent
    add column if not exists livemode boolean not null default false,
    add column if not exists failure_reason_code text,
    add column if not exists stripe_object_id text;

alter table public.stripeevent drop constraint if exists stripeevent_status_check;
alter table public.stripeevent add constraint stripeevent_status_check
    check (status in ('received', 'processing', 'processed', 'failed', 'observed_pending'));
create index if not exists stripeevent_stripe_object_id_idx
    on public.stripeevent(stripe_object_id);

create table if not exists public.paymentcheckoutrate (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    idempotency_key_hash text not null,
    package_code text not null,
    status text not null default 'reserved' check (status in ('reserved', 'completed', 'released')),
    stripe_checkout_session_id text unique,
    created_at timestamptz not null default now(),
    released_at timestamptz,
    unique (user_id, idempotency_key_hash)
);
create index if not exists paymentcheckoutrate_user_created_idx
    on public.paymentcheckoutrate(user_id, created_at);

create table if not exists public.paymentoperationaudit (
    id bigint generated by default as identity primary key,
    admin_user_id uuid not null references auth.users(id),
    operation text not null,
    target_type text not null,
    target_id text not null,
    before_status text,
    after_status text,
    result text not null,
    reason text,
    created_at timestamptz not null default now()
);
create index if not exists paymentoperationaudit_target_idx
    on public.paymentoperationaudit(target_type, target_id, created_at);

alter table public.purchase enable row level security;
alter table public.stripeevent enable row level security;
alter table public.paymentcheckoutrate enable row level security;
alter table public.paymentoperationaudit enable row level security;

revoke all on public.purchase, public.stripeevent, public.paymentcheckoutrate,
    public.paymentoperationaudit from public, anon, authenticated;
grant select, insert, update, delete on public.purchase, public.stripeevent,
    public.paymentcheckoutrate to service_role;
grant select, insert on public.paymentoperationaudit to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
