begin;

lock table public.packcreditaccount, public.generationusage, public.purchase,
    public.packcreditledger in share row exclusive mode;

alter table public.packcreditaccount add column if not exists lot_backfilled_at timestamptz;

create table if not exists public.packcreditlot (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    source_ledger_id bigint not null unique references public.packcreditledger(id),
    purchase_id bigint references public.purchase(id),
    source_type text not null check (source_type in ('free', 'manual', 'stripe')),
    granted_credits integer not null check (granted_credits > 0),
    remaining_credits integer not null check (remaining_credits >= 0 and remaining_credits <= granted_credits),
    refundable boolean not null default false,
    refunded boolean not null default false,
    created_at timestamptz not null
);

create table if not exists public.packcreditallocation (
    id bigint generated by default as identity primary key,
    lot_id bigint not null references public.packcreditlot(id),
    user_id uuid not null references auth.users(id) on delete cascade,
    pack_id uuid not null,
    credits integer not null check (credits > 0),
    status text not null check (status in ('reserved', 'completed', 'released')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (lot_id, pack_id)
);

create table if not exists public.paymentrefund (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id),
    purchase_id bigint not null unique references public.purchase(id),
    status text not null check (status in (
        'requested', 'processing', 'reconciling', 'succeeded', 'failed', 'rejected', 'dispute_pending'
    )),
    currency text not null check (currency = 'AUD'),
    requested_amount_cents integer not null check (requested_amount_cents >= 0),
    refunded_amount_cents integer check (refunded_amount_cents is null or refunded_amount_cents >= 0),
    actual_stripe_fee_cents integer check (actual_stripe_fee_cents is null or actual_stripe_fee_cents >= 0),
    stripe_refund_id text unique,
    stripe_idempotency_key text not null unique,
    processing_lease_expires_at timestamptz,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    completed_at timestamptz
);

create index if not exists paymentrefund_user_status_created_idx
    on public.paymentrefund(user_id, status, created_at desc);
create index if not exists paymentrefund_processing_lease_idx
    on public.paymentrefund(processing_lease_expires_at)
    where status in ('processing', 'reconciling');
create index if not exists packcreditallocation_user_pack_idx
    on public.packcreditallocation(user_id, pack_id);

alter table public.packcreditlot enable row level security;
alter table public.packcreditallocation enable row level security;
alter table public.paymentrefund enable row level security;
revoke all on public.packcreditlot, public.packcreditallocation, public.paymentrefund
    from public, anon, authenticated;
revoke all on sequence public.packcreditlot_id_seq, public.packcreditallocation_id_seq,
    public.paymentrefund_id_seq from public, anon, authenticated;
grant select, insert, update, delete on public.packcreditlot, public.packcreditallocation,
    public.paymentrefund to service_role;
grant usage, select on sequence public.packcreditlot_id_seq, public.packcreditallocation_id_seq,
    public.paymentrefund_id_seq to service_role;

insert into public.packcreditlot(
    user_id, source_ledger_id, purchase_id, source_type, granted_credits,
    remaining_credits, refundable, created_at
)
select user_id, id, purchase_id,
    case entry_type when 'grant_free' then 'free' when 'grant_manual_topup' then 'manual' else 'stripe' end,
    credits_delta, credits_delta, entry_type = 'grant_stripe_purchase', created_at
from public.packcreditledger
where entry_type in ('grant_free', 'grant_manual_topup', 'grant_stripe_purchase')
on conflict (source_ledger_id) do nothing;

do $$
declare
    v_debit record;
    v_lot record;
    v_usage_status text;
    v_needed integer;
    v_take integer;
    v_allocation_status text;
begin
    if exists (
        select 1 from public.packcreditledger r
        where r.entry_type = 'release' and not exists (
            select 1 from public.packcreditledger d
            where d.user_id = r.user_id and d.pack_id = r.pack_id and d.entry_type = 'debit_generation'
        )
    ) then raise exception 'Ambiguous historical release without debit'; end if;
    if exists (
        select 1 from public.packcreditledger where entry_type = 'release'
        group by user_id, pack_id having count(*) > 1
    ) then raise exception 'Duplicate historical release'; end if;

    for v_debit in
        select * from public.packcreditledger where entry_type = 'debit_generation'
        order by created_at, id
    loop
        if exists (select 1 from public.packcreditallocation where user_id = v_debit.user_id and pack_id = v_debit.pack_id) then
            continue;
        end if;
        select status into v_usage_status from public.generationusage
        where user_id = v_debit.user_id and pack_id = v_debit.pack_id;
        if v_usage_status is null then raise exception 'Debit has no generation usage'; end if;
        v_allocation_status := case when v_usage_status = 'reserved' then 'reserved'
            when v_usage_status = 'released' then 'released' else 'completed' end;
        v_needed := -v_debit.credits_delta;
        for v_lot in
            select * from public.packcreditlot
            where user_id = v_debit.user_id and remaining_credits > 0
            order by created_at, id for update
        loop
            exit when v_needed = 0;
            v_take := least(v_needed, v_lot.remaining_credits);
            insert into public.packcreditallocation(lot_id, user_id, pack_id, credits, status, created_at)
            values (v_lot.id, v_debit.user_id, v_debit.pack_id, v_take, v_allocation_status, v_debit.created_at);
            if v_allocation_status <> 'released' then
                update public.packcreditlot set remaining_credits = remaining_credits - v_take where id = v_lot.id;
            end if;
            v_needed := v_needed - v_take;
        end loop;
        if v_needed <> 0 then raise exception 'Insufficient lot history for debit %', v_debit.id; end if;
    end loop;
end;
$$;

update public.packcreditaccount a
set balance = balance + coalesce((
    select sum(credits) from public.packcreditallocation x
    where x.user_id = a.user_id and x.status = 'reserved'
), 0), lot_backfilled_at = now(), updated_at = now()
where lot_backfilled_at is null;
alter table public.packcreditaccount alter column lot_backfilled_at set default now();

do $$ begin
    if exists (
        select 1 from public.packcreditaccount a
        where a.balance <> coalesce((select sum(remaining_credits) from public.packcreditlot l where l.user_id = a.user_id), 0)
            + coalesce((select sum(credits) from public.packcreditallocation x where x.user_id = a.user_id and x.status = 'reserved'), 0)
    ) then raise exception 'Pack credit account and lot history do not reconcile'; end if;
end $$;

create or replace function public.create_pack_credit_lot_from_grant()
returns trigger language plpgsql security invoker set search_path = public as $$
begin
    if new.entry_type in ('grant_free', 'grant_manual_topup', 'grant_stripe_purchase') then
        insert into public.packcreditlot(user_id, source_ledger_id, purchase_id, source_type,
            granted_credits, remaining_credits, refundable, created_at)
        values (new.user_id, new.id, new.purchase_id,
            case new.entry_type when 'grant_free' then 'free' when 'grant_manual_topup' then 'manual' else 'stripe' end,
            new.credits_delta, new.credits_delta, new.entry_type = 'grant_stripe_purchase', new.created_at)
        on conflict (source_ledger_id) do nothing;
    end if;
    return new;
end;
$$;
drop trigger if exists packcreditledger_create_lot on public.packcreditledger;
create trigger packcreditledger_create_lot after insert on public.packcreditledger
for each row execute function public.create_pack_credit_lot_from_grant();

create or replace function public.get_available_pack_credits(p_user_id uuid)
returns integer language sql security invoker set search_path = public as $$
    select greatest(0, a.balance - coalesce((
        select sum(x.credits) from public.packcreditallocation x
        where x.user_id = p_user_id and x.status = 'reserved'
    ), 0)) from public.packcreditaccount a where a.user_id = p_user_id
$$;

create or replace function public.reserve_pack_credits(
    p_user_id uuid, p_pack_id uuid, p_credit_cost integer, p_monthly_limit integer default 500
) returns table(result_status text, remaining_balance integer)
language plpgsql security invoker set search_path = public as $$
declare
    v_available integer;
    v_month date := date_trunc('month', timezone('UTC', now()))::date;
    v_reserved integer;
    v_completed integer;
    v_lot record;
    v_needed integer := p_credit_cost;
    v_take integer;
begin
    if p_credit_cost not in (1, 2) then raise exception 'Pack credit cost must be 1 or 2'; end if;
    perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));
    insert into public.packcreditaccount(user_id, balance) values (p_user_id, 2) on conflict do nothing;
    if found then
        insert into public.packcreditledger(user_id, entry_type, credits_delta, idempotency_key, note)
        values (p_user_id, 'grant_free', 2, 'grant-free:' || p_user_id, 'Initial lifetime credits') on conflict do nothing;
    end if;
    perform 1 from public.packcreditaccount where user_id = p_user_id for update;
    v_available := public.get_available_pack_credits(p_user_id);
    if exists (select 1 from public.generationusage where user_id = p_user_id and pack_id = p_pack_id) then
        return query select 'existing'::text, v_available; return;
    end if;
    if v_available < p_credit_cost then
        return query select 'insufficient_credits'::text, v_available; return;
    end if;
    insert into public.globalmonthlyusage(month_start) values (v_month) on conflict do nothing;
    select reserved_count, completed_count into v_reserved, v_completed
    from public.globalmonthlyusage where month_start = v_month for update;
    if v_reserved + v_completed >= p_monthly_limit then
        return query select 'global_limit'::text, v_available; return;
    end if;
    insert into public.packcreditledger(user_id, entry_type, credits_delta, pack_id, idempotency_key)
    values (p_user_id, 'debit_generation', -p_credit_cost, p_pack_id,
        'generation:' || p_user_id || ':' || p_pack_id);
    for v_lot in select * from public.packcreditlot
        where user_id = p_user_id and remaining_credits > 0 order by created_at, id for update
    loop
        exit when v_needed = 0;
        v_take := least(v_needed, v_lot.remaining_credits);
        update public.packcreditlot set remaining_credits = remaining_credits - v_take where id = v_lot.id;
        insert into public.packcreditallocation(lot_id, user_id, pack_id, credits, status)
        values (v_lot.id, p_user_id, p_pack_id, v_take, 'reserved');
        v_needed := v_needed - v_take;
    end loop;
    if v_needed <> 0 then raise exception 'Lot balance mismatch'; end if;
    insert into public.generationusage(user_id, pack_id, generated_at, status, credit_cost,
        reserved_at, expires_at, usage_month)
    values (p_user_id, p_pack_id, now(), 'reserved', p_credit_cost, now(), now() + interval '30 minutes', v_month);
    update public.globalmonthlyusage set reserved_count = reserved_count + 1, updated_at = now()
    where month_start = v_month;
    return query select 'reserved'::text, public.get_available_pack_credits(p_user_id);
end;
$$;

create or replace function public.complete_pack_credits(p_user_id uuid, p_pack_id uuid)
returns boolean language plpgsql security invoker set search_path = public as $$
declare v_usage public.generationusage%rowtype;
begin
    perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));
    select * into v_usage from public.generationusage
    where user_id = p_user_id and pack_id = p_pack_id and status = 'reserved' for update;
    if not found then return false; end if;
    update public.packcreditallocation set status = 'completed', updated_at = now()
    where user_id = p_user_id and pack_id = p_pack_id and status = 'reserved';
    update public.packcreditaccount set balance = balance - v_usage.credit_cost, updated_at = now()
    where user_id = p_user_id;
    update public.generationusage set status = 'completed', completed_at = now() where id = v_usage.id;
    update public.globalmonthlyusage set reserved_count = reserved_count - 1,
        completed_count = completed_count + 1, updated_at = now()
    where month_start = v_usage.usage_month and reserved_count > 0;
    return true;
end;
$$;

create or replace function public.release_pack_credits(p_user_id uuid, p_pack_id uuid)
returns boolean language plpgsql security invoker set search_path = public as $$
declare v_usage public.generationusage%rowtype;
begin
    perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));
    select * into v_usage from public.generationusage
    where user_id = p_user_id and pack_id = p_pack_id and status = 'reserved' for update;
    if not found then return false; end if;
    if exists (select 1 from public.packcreditallocation x join public.packcreditlot l on l.id = x.lot_id
        where x.user_id = p_user_id and x.pack_id = p_pack_id and x.status = 'reserved' and l.refunded) then
        raise exception 'Cannot release credits to a refunded lot';
    end if;
    update public.packcreditlot l set remaining_credits = remaining_credits + x.credits
    from public.packcreditallocation x
    where x.lot_id = l.id and x.user_id = p_user_id and x.pack_id = p_pack_id and x.status = 'reserved';
    update public.packcreditallocation set status = 'released', updated_at = now()
    where user_id = p_user_id and pack_id = p_pack_id and status = 'reserved';
    update public.generationusage set status = 'released', released_at = now() where id = v_usage.id;
    update public.globalmonthlyusage set reserved_count = reserved_count - 1, updated_at = now()
    where month_start = v_usage.usage_month and reserved_count > 0;
    insert into public.packcreditledger(user_id, entry_type, credits_delta, pack_id, idempotency_key)
    values (p_user_id, 'release', v_usage.credit_cost, p_pack_id, 'release:' || p_user_id || ':' || p_pack_id)
    on conflict (idempotency_key) do nothing;
    return true;
end;
$$;

revoke all on function public.create_pack_credit_lot_from_grant() from public, anon, authenticated;
revoke all on function public.get_available_pack_credits(uuid) from public, anon, authenticated;
revoke all on function public.reserve_pack_credits(uuid, uuid, integer, integer) from public, anon, authenticated;
revoke all on function public.complete_pack_credits(uuid, uuid) from public, anon, authenticated;
revoke all on function public.release_pack_credits(uuid, uuid) from public, anon, authenticated;
grant execute on function public.get_available_pack_credits(uuid) to service_role;
grant execute on function public.reserve_pack_credits(uuid, uuid, integer, integer) to service_role;
grant execute on function public.complete_pack_credits(uuid, uuid) to service_role;
grant execute on function public.release_pack_credits(uuid, uuid) to service_role;

commit;
